#!/bin/bash

set -euo pipefail

function testall() {
    cd lib/tests && make
    cd ../..
    cd src/chapter3 && make
    cd ../..
    cd src/chapter4 && make
    cd ../..
    cd src/chapter5 && make
    cd ../..
    cd src/chapter6 && make
    cd ../..
    cd src/chapter7 && make
    cd ../..
    cd src/chapter9 && make
    cd ../..
}

function testlib() {
    cd lib/tests && make $1
}

function testsrc() {
    case $1 in
    "3") cd src/chapter3 && make ;;
    "4") cd src/chapter4 && make ;;
    "5") cd src/chapter5 && make ;;
    "6") cd src/chapter6 && make ;;
    "7") cd src/chapter7 && make ;;
    "9") cd src/chapter9 && make ;;
    "graph") cd src/graph && make test;;
    *) echo unimplemeted ;;
    esac
}

case $1 in
"all") testall ;;
"lib") testlib $2 ;;
"src") testsrc $2 ;;
esac
