name: cpp CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Test cpp source
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test lib
        env:
          CC: gcc
        run: | 
          export GUMPTION=$(pwd)
          cd lib/tests/
          make test
