name: cpp CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Test cpp source
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test lib
        env:
          CC: gcc
        run: | 
          export GUMPTION=$(pwd)
          cd lib/tests/
          make test
      - name: test chaining_hash 
        env:
          CC: gcc
        run: |
          export GUMPTION=$(pwd)
          cd src/chapter4/ch4.1
          make test
      - name: test sort 
        env:
          CC: gcc
        run: |
          export GUMPTION=$(pwd)
          cd src/chapter5/
          make test
      - name: test binary_heap
        env:
          CC: gcc
        run: |
          export GUMPTION=$(pwd)
          cd src/chapter6/
          make test
      - name: test binary_search_tree
        env:
          CC: gcc
        run: |
          export GUMPTION=$(pwd)
          cd src/chapter7/
          make test
